### ISSUE TITLE
tests failing when connected to VPN

### ISSUE THREAD

**Issue by kumavis** [ipfs/js-libp2p-ipfs-browser#122]
1) libp2p-ipfs-browser (webrtc only) dial from the second node to the first node:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
2) libp2p-ipfs-browser (webrtc only) node1 hangUp node2:
     Error: Uncaught AssertionError: expected true to not exist

```
╰─$ npm run test:browser                                                                                                                                                        

> libp2p-ipfs-browser@0.16.0 test:browser /Users/kumavis/dev/js-libp2p-ipfs-browser
> gulp test:browser

[14:10:13] Using gulpfile ~/dev/js-libp2p-ipfs-browser/gulpfile.js
[14:10:13] Starting 'test:browser'...
[14:10:13] Starting 'libnode:start'...
[14:10:14] Finished 'libnode:start' after 144 ms
[14:10:14] Starting 'test:browser:before'...
[14:10:14] Finished 'test:browser:before' after 6.68 μs
[14:10:14] Starting 'karma'...


15 11 2016 14:10:15.003:WARN [watcher]: Pattern "/Users/kumavis/dev/js-libp2p-ipfs-browser/test/**/*.spec.js" does not match any file.
15 11 2016 14:10:15.005:WARN [watcher]: Pattern "/Users/kumavis/dev/js-libp2p-ipfs-browser/test/fixtures/**/*" does not match any file.
15 11 2016 14:10:21.580:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
15 11 2016 14:10:21.580:INFO [launcher]: Launching browser Chrome with concurrency 1
15 11 2016 14:10:21.586:INFO [launcher]: Starting browser Chrome
15 11 2016 14:10:23.641:INFO [Chrome 54.0.2840 (Mac OS X 10.10.5)]: Connected on socket /#Jzlh0kAh8zpJWeljAAAA with id 79955531
  libp2p-ipfs-browser (websockets only)
    ✓ create libp2pNode (607ms)
    ✓ start libp2pNode (1ms)
    ✓ libp2p.dialByMultiaddr nodeA to nodeB (639ms)
    ✓ libp2p.dialByMultiaddr on Protocol nodeA to nodeB (53ms)
    ✓ libp2p.hangupByMultiaddr nodeA to nodeB (506ms)
    ✓ libp2p.dialByPeerInfo nodeA to nodeB (561ms)
    ✓ libp2p.dialByPeerInfo on Protocol nodeA to nodeB (26ms)
    ✓ libp2p.hangupByPeerInfo nodeA to nodeB (503ms)
    - libp2p.dialById nodeA to nodeB
    - libp2p.dialById on Protocol nodeA to nodeB
    - libp2p.hangupById nodeA to nodeB
    stress
      ✓ one big write (4289ms)
      ✓ many writes (1553ms)

  libp2p-ipfs-browser (webrtc only)
    ✓ create two peerInfo with webrtc-star addrs (667ms)
    ✓ create two libp2p nodes with those peers (2ms)
    ✓ listen on the two libp2p nodes (23ms)
    ✓ handle a protocol on the first node
    1) dial from the second node to the first node
    2) node1 hangUp node2
    ✓ create a third node and check that discovery works


  15 passing (34s)
  3 pending
  2 failing

  1) libp2p-ipfs-browser (webrtc only) dial from the second node to the first node:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.

  

  2) libp2p-ipfs-browser (webrtc only) node1 hangUp node2:
     Error: Uncaught AssertionError: expected true to not exist (webpack:///~/chai/lib/chai/assertion.js:107:0 <- test/browser.js:63401)

  



[14:10:49] 'karma' errored after 35 s
[14:10:49] Error: Some tests are failing
    at formatError (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/orchestrator/index.js:264:8)
    at /Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/orchestrator/lib/runTask.js:29:3)
    at Server (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/aegir/tasks/test/browser.js:21:7)
    at removeAllListeners (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/karma/lib/server.js:379:7)
    at Server.<anonymous> (/Users/kumavis/dev/js-libp2p-ipfs-browser/node_modules/karma/lib/server.js:390:9)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1548:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/kumavis/.nvm/versions/node/v6.3.1/bin/node" "/Users/kumavis/.nvm/versions/node/v6.3.1/bin/npm" "run" "test:browser"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! libp2p-ipfs-browser@0.16.0 test:browser: `gulp test:browser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libp2p-ipfs-browser@0.16.0 test:browser script 'gulp test:browser'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libp2p-ipfs-browser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test:browser
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libp2p-ipfs-browser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libp2p-ipfs-browser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kumavis/dev/js-libp2p-ipfs-browser/npm-debug.log
```

**Comment by kumavis** [comment]
So after much debugging, seems the IceConnection is failing inside of `simple-peer`. No idea why.

**Comment by dignifiedquire** [comment]
@kumavis is this `master` or any other version?

**Comment by kumavis** [comment]
master - shoot what branch was i supposed to be using?

**Comment by diasdavid** [comment]
I see you are using npm 3, so it should be good.

I just did a fresh clone, fresh npm install and everything is working fine:

```
  libp2p-ipfs-browser (websockets only)
    ✓ create libp2pNode (245ms)
    ✓ start libp2pNode (1ms)
    ✓ libp2p.dialByMultiaddr nodeA to nodeB (622ms)
    ✓ libp2p.dialByMultiaddr on Protocol nodeA to nodeB (31ms)
    ✓ libp2p.hangupByMultiaddr nodeA to nodeB (504ms)
    ✓ libp2p.dialByPeerInfo nodeA to nodeB (548ms)
    ✓ libp2p.dialByPeerInfo on Protocol nodeA to nodeB (20ms)
    ✓ libp2p.hangupByPeerInfo nodeA to nodeB (503ms)
    - libp2p.dialById nodeA to nodeB
    - libp2p.dialById on Protocol nodeA to nodeB
    - libp2p.hangupById nodeA to nodeB
    stress
      ✓ one big write (2910ms)
      ✓ many writes (1513ms)

  libp2p-ipfs-browser (webrtc only)
    ✓ create two peerInfo with webrtc-star addrs (1120ms)
    ✓ create two libp2p nodes with those peers (2ms)
    ✓ listen on the two libp2p nodes (21ms)
    ✓ handle a protocol on the first node
    ✓ dial from the second node to the first node (767ms)
    ✓ node1 hangUp node2 (502ms)
    ✓ create a third node and check that discovery works (2338ms)


  17 passing (17s)
  3 pending
```

CI is also fine https://travis-ci.org/ipfs/js-libp2p-ipfs-browser/jobs/176329622

Can you try to npm fresh install?

**Comment by VictorBjelkholm** [comment]
I also tried running the tests on a fresh clone from master (950a9ad3f415b3c7284ef5a93715ef0df1d58a3b currently) and tests are failing for me as well, but with different error and also a worrisome discovery.

Firstly, error in the test involves webpack:
```
17 11 2016 11:36:10.134:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: [
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   ]
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
```

Secondly, the exit code from running the tests is 0! Which in reality should mean the tests are passing, but they are not.

Full logs:
```
➜  js-libp2p-ipfs-browser git:(master) npm test   

> libp2p-ipfs-browser@0.12.1 test /home/victor/projects/ipfs/js-libp2p-ipfs-browser
> gulp test

[11:35:58] Using gulpfile ~/projects/ipfs/js-libp2p-ipfs-browser/gulpfile.js
[11:35:58] Starting 'test'...
[11:35:58] Starting 'test:node'...
[11:35:58] Starting 'libnode:start'...
[11:35:58] Finished 'libnode:start' after 78 ms
[11:35:58] Starting 'test:node:before'...
[11:35:58] Finished 'test:node:before' after 4.52 μs
[11:35:58] Starting 'mocha'...


  libp2p-ipfs-browser (websockets only)
    ✓ create libp2pNode (3484ms)
    ✓ start libp2pNode
    ✓ libp2p.dialByMultiaddr nodeA to nodeB (579ms)
    ✓ libp2p.dialByMultiaddr on Protocol nodeA to nodeB
    ✓ libp2p.hangupByMultiaddr nodeA to nodeB (506ms)
    ✓ libp2p.dialByPeerInfo nodeA to nodeB (517ms)
    ✓ libp2p.dialByPeerInfo on Protocol nodeA to nodeB
    ✓ libp2p.hangupByPeerInfo nodeA to nodeB (501ms)
    - libp2p.dialById nodeA to nodeB
    - libp2p.dialById on Protocol nodeA to nodeB
    - libp2p.hangupById nodeA to nodeB
    ✓ stress test: one big write (226ms)
    ✓ stress test: many writes in 2 batches (3210ms)
    ✓ stop the libp2pnode


  11 passing (9s)
  3 pending

[11:36:07] Finished 'mocha' after 9.58 s
[11:36:07] Starting 'libnode:stop'...
[11:36:09] Finished 'libnode:stop' after 2.01 s
[11:36:09] Starting 'test:node:after'...
[11:36:09] Finished 'test:node:after' after 4.89 μs
[11:36:09] Finished 'test:node' after 12 s
[11:36:09] Starting 'test:browser'...
[11:36:09] Starting 'libnode:start'...
[11:36:09] Finished 'libnode:start' after 7.19 ms
[11:36:09] Starting 'test:browser:before'...
[11:36:09] Finished 'test:browser:before' after 2.22 μs
[11:36:09] Starting 'karma'...
17 11 2016 11:36:10.134:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: [
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   ]
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/webpack/lib/webpack.js:17:9)
    at new Plugin (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:59:20)
    at get (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:48:43)
    at /home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:75:15)
    at get (/home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:48:43)
    at /home/victor/projects/ipfs/js-libp2p-ipfs-browser/node_modules/di/lib/injector.js:71:14
    at Array.map (native)


17 11 2016 11:36:10.157:WARN [watcher]: Pattern "/home/victor/projects/ipfs/js-libp2p-ipfs-browser/test/**/*.spec.js" does not match any file.
17 11 2016 11:36:10.172:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
17 11 2016 11:36:10.173:INFO [launcher]: Launching browsers Chrome, PhantomJS with concurrency 1
17 11 2016 11:36:10.173:ERROR [karma]: Found 1 load error
[11:36:10] Finished 'karma' after 234 ms
[11:36:10] Starting 'libnode:stop'...
[11:36:12] Finished 'libnode:stop' after 2 s
[11:36:12] Starting 'test:browser:after'...
[11:36:12] Finished 'test:browser:after' after 3.01 μs
[11:36:12] Finished 'test:browser' after 2.24 s
[11:36:12] Finished 'test' after 14 s
➜  js-libp2p-ipfs-browser git:(master) echo $?                  
0
➜  js-libp2p-ipfs-browser git:(master) npm version
{ 'libp2p-ipfs-browser': '0.12.1',
  npm: '4.0.1',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.6.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.83',
  zlib: '1.2.8' }
```

**Comment by VictorBjelkholm** [comment]
Output from `npm ls` as well: https://ipfs.io/ipfs/QmQptqPxRzkBNMs3L3mxLm9hfN9VZLxRMvX2RrQoKRWNmH/npm-ls-output.log

**Comment by VictorBjelkholm** [comment]
Reminder to self: check that the commits you refer to as latest are actually the latest... Updated from master and now the tests are passing for me.

**Comment by kumavis** [comment]
retried, I'm getting failures still
https://gist.github.com/kumavis/559da6afd60c456f9c7ba01c1f844220

only on karma
17 11 2016 12:45:48.155:INFO [Chrome 54.0.2840 (Mac OS X 10.10.5)]:

on latest master with fresh npm i

**Comment by kumavis** [comment]
how can i help debug this issue?

**Comment by kumavis** [comment]
For those the tests pass for, can you report what browser version the tests run on?

**Comment by kumavis** [comment]
Hey! - Tests pass when I disconnect from my VPN....

**Comment by diasdavid** [comment]
Ah, that makes sense, since the sig server is on localhost ! :) All good then?

**Comment by kumavis** [comment]
@diasdavid well, i can still access localhost over http, not really sure why it doesnt work for webrtc, but its a bit out of scope for this project

**Comment by diasdavid** [comment]
@kumavis it is how the STUN in WebRTC happens, it is getting confused, getting SDP offers for IPFS where it is not located, making the dialing fail.

**Comment by kumavis** [comment]
technology is a bottomless pit spewing lasers :hole: ⚡️  ⚡️
